url: salasdeestudoteresina.com.br
baseurl:
#url: localhost:4000

# Site settings
title: SET
email: set@gmail.com
description: "SET seu ambiente de estudo em Teresina"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff0000
  secondary: ff4500
  secondary-dark: ff6347



# Team names, titles and social links
people:
- name: Wellane Aragão
  pic: 1
  position: "Encontrar um local que propicie uma boa rotina de estudo não é facil. A proximidade da minha residência, a facilidade de estacionamento, a tranquilidade, o conforto e a segurança que a SET proporciona aumenta a qualidade dos meus estudos."


- name: Simone Midoura
  pic: 2
  position: "Estudar na SET me deu a senação de terminar o dia sabendo que estou fazendo a coisa certa, da maneira certa e , principalmente, no lugar certo. Ter um espaço estuturado me procporcionou um estudo com mais qualidade e ânimo. Sem dúvidas, a SET está sendo imprescindível nessa caminhada!"

- name: Enediana Chagas
  pic: 3
  position: "O caminho para alcançar o objetivo que almejamos torna-se mais dificil quando temos uma vida corrida. Pensando nisso, procurei a SET. Lá, eu encontrei tudo que precisava para concretizar meus planos: um ambiente de estudo de excelência, pessoas acolhedoras e concurseiros que, assimo como eu, buscam o tão sonhado cargo público."



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/Salas-de-Estudo-Teresina-SET-1405771563078562
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: instagram
    url: https://instagram.com/salasdeestudoteresina/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty